--
- include_vars: "{{ ansible_distribution }}.yml"

- name: Microsoft Repository (RedHat)
  block:
    - name: Microsoft Repository GPG key
      rpm_key:
        key: https://packages.microsoft.com/keys/microsoft.asc
        state: present

    - name: Microsoft Repository
      yum_repository:
        name: vscode
        description: Visual Studio Code
        baseurl: https://packages.microsoft.com/yumrepos/vscode/
        enabled: yes
        gpgcheck : yes
        gpgkey: https://packages.microsoft.com/keys/microsoft.asc
  when:
    - ansible_os_family == "RedHat"

- name: Install package
  package:
    name: "{{packages}}"
    state: latest
  when:
    - ansible_os_family != "Archlinux"

- name: Install package (Arch Linux)
  aur:
    use: yay
    state: present
    name: "{{packages}}"
  become: yes
  become_user: aur_builder
  when:
    - ansible_os_family == "Archlinux"
...